[theme]
theme = "solarized-dark"
[icons]
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_avail.eng(prefix:M)/$mem_total.eng(prefix:M)($mem_total_used_percents.eng(w:2)) "

[[block]]
block = "cpu"
interval = 1
format = " $icon $frequency "

[[block]]
block = "load"
interval = 1
format = " $icon $1m.eng(w:4) | $5m.eng(w:4) | $15m.eng(w:4) "

[[block]]
block = "temperature"
interval = 10
scale = "celsius"
format = "$icon $average° "
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "sound"

#[[block]]
#block = "battery"
#interval = 10
#format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%R %a %d/%m', l:fr_BE) "
