live_config_reload = true

import = [
       "~/.config/alacritty/solarized_light.toml"
]

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 17.0

[font.bold]
family = "FiraCode Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[font.offset]
x = 0
y = 0

[keyboard]
bindings = [
    { action = "Paste", key = "V", mods = "Command" }
    { action = "Copy",key = "C",mods = "Command"}
    {action = "Quit",key = "Q",mods = "Command"}
    {action = "SpawnNewInstance",key = "N",mods = "Command"}
    {action = "ToggleFullscreen",key = "Return",mods = "Command"}
    {chars = "\u001BOH",key = "Home",mode = "AppCursor"}
    {chars = "\u001B[H",key = "Home",mode = "~AppCursor"}
    {chars = "\u001BOF",key = "End",mode = "AppCursor"}
    {chars = "\u001B[F",key = "End",mode = "~AppCursor"}
    {action = "IncreaseFontSize",key = "Equals",mods = "Command"}
    {action = "DecreaseFontSize",key = "Minus",mods = "Command"}
    {action = "ResetFontSize",key = "Minus",mods = "Command|Shift"}
    {chars = "\u001B[5;2~",key = "PageUp",mods = "Shift"}
    {chars = "\u001B[5;5~",key = "PageUp",mods = "Control"}
    {chars = "\u001B[5~",key = "PageUp"}
    {chars = "\u001B[6;2~",key = "PageDown",mods = "Shift"}
    {chars = "\u001B[6;5~",key = "PageDown",mods = "Control"}
    {chars = "\u001B[6~",key = "PageDown"}
    {chars = "\u001B[1;2D",key = "Left",mods = "Shift"}
    {chars = "\u001B[1;5D",key = "Left",mods = "Control"}
    {chars = "\u001B[1;3D",key = "Left",mods = "Alt"}
    {chars = "\u001B[D",key = "Left",mode = "~AppCursor"}
    {chars = "\u001BOD",key = "Left",mode = "AppCursor"}
    {chars = "\u001B[1;2C",key = "Right",mods = "Shift"}
    {chars = "\u001B[1;5C",key = "Right",mods = "Control"}
    {chars = "\u001B[1;3C",key = "Right",mods = "Alt"}
    {chars = "\u001B[C",key = "Right",mode = "~AppCursor"}
    {chars = "\u001BOC",key = "Right",mode = "AppCursor"}
    {chars = "\u001B[1;2A",key = "Up",mods = "Shift"}
    {chars = "\u001B[1;5A",key = "Up",mods = "Control"}
    {chars = "\u001B[1;3A",key = "Up",mods = "Alt"}
    {chars = "\u001B[A",key = "Up",mode = "~AppCursor"}
    {chars = "\u001BOA",key = "Up",mode = "AppCursor"}
    {chars = "\u001B[1;2B",key = "Down",mods = "Shift"}
    {chars = "\u001B[1;5B",key = "Down",mods = "Control"}
    {chars = "\u001B[1;3B",key = "Down",mods = "Alt"}
    {chars = "\u001B[B",key = "Down",mode = "~AppCursor"}
    {chars = "\u001BOB",key = "Down",mode = "AppCursor"}
    {chars = "\u001B[Z",key = "Tab",mods = "Shift"}
    {chars = "\u001BOP",key = "F1"}
    {chars = "\u001BOQ",key = "F2"}
    {chars = "\u001BOR",key = "F3"}
    {chars = "\u001BOS",key = "F4"}
    {chars = "\u001B[15~",key = "F5"}
    {chars = "\u001B[17~",key = "F6"}
    {chars = "\u001B[18~",key = "F7"}
    {chars = "\u001B[19~",key = "F8"}
    {chars = "\u001B[20~",key = "F9"}
    {chars = "\u001B[21~",key = "F10"}
    {chars = "\u001B[23~",key = "F11"}
    {chars = "\u001B[24~",key = "F12"}
    {chars = "\u007F",key = "Back"}
    {chars = "\u001B\u007F",key = "Back",mods = "Alt"}
    {chars = "\u001B[2~",key = "Insert"}
    {chars = "\u001B[3~",key = "Delete"}
    {chars = "\u001Ba",key = "A",mods = "Alt"}
    {chars = "\u001Bb",key = "B",mods = "Alt"}
    {chars = "\u001Bc",key = "C",mods = "Alt"}
    {chars = "\u001Bd",key = "D",mods = "Alt"}
    {chars = "\u001Be",key = "E",mods = "Alt"}
    {chars = "\u001Bf",key = "F",mods = "Alt"}
    {chars = "\u001Bg",key = "G",mods = "Alt"}
    {chars = "\u001Bh",key = "H",mods = "Alt"}
    {chars = "\u001Bi",key = "I",mods = "Alt"}
    {chars = "\u001Bj",key = "J",mods = "Alt"}
    {chars = "\u001Bk",key = "K",mods = "Alt"}
    {chars = "\u001Bl",key = "L",mods = "Alt"}
    {chars = "\u001Bm",key = "M",mods = "Alt"}
    {chars = "\u001Bn",key = "N",mods = "Alt"}
    {chars = "\u001Bo",key = "O",mods = "Alt"}
    {chars = "\u001Bp",key = "P",mods = "Alt"}
    {chars = "\u001Bq",key = "Q",mods = "Alt"}
    {chars = "\u001Br",key = "R",mods = "Alt"}
    {chars = "\u001Bs",key = "S",mods = "Alt"}
    {chars = "\u001Bt",key = "T",mods = "Alt"}
    {chars = "\u001Bu",key = "U",mods = "Alt"}
    {chars = "\u001Bv",key = "V",mods = "Alt"}
    {chars = "\u001Bw",key = "W",mods = "Alt"}
    {chars = "\u001Bx",key = "X",mods = "Alt"}
    {chars = "\u001By",key = "Y",mods = "Alt"}
    {chars = "\u001Bz",key = "Z",mods = "Alt"}
    {chars = "\u001BA",key = "A",mods = "Alt|Shift"}
    {chars = "\u001BB",key = "B",mods = "Alt|Shift"}
    {chars = "\u001BC",key = "C",mods = "Alt|Shift"}
    {chars = "\u001BD",key = "D",mods = "Alt|Shift"}
    {chars = "\u001BE",key = "E",mods = "Alt|Shift"}
    {chars = "\u001BF",key = "F",mods = "Alt|Shift"}
    {chars = "\u001BG",key = "G",mods = "Alt|Shift"}
    {chars = "\u001BH",key = "H",mods = "Alt|Shift"}
    {chars = "\u001BI",key = "I",mods = "Alt|Shift"}
    {chars = "\u001BJ",key = "J",mods = "Alt|Shift"}
    {chars = "\u001BK",key = "K",mods = "Alt|Shift"}
    {chars = "\u001BL",key = "L",mods = "Alt|Shift"}
    {chars = "\u001BM",key = "M",mods = "Alt|Shift"}
    {chars = "\u001BN",key = "N",mods = "Alt|Shift"}
    {chars = "\u001BO",key = "O",mods = "Alt|Shift"}
    {chars = "\u001BP",key = "P",mods = "Alt|Shift"}
    {chars = "\u001BQ",key = "Q",mods = "Alt|Shift"}
    {chars = "\u001BR",key = "R",mods = "Alt|Shift"}
    {chars = "\u001BS",key = "S",mods = "Alt|Shift"}
    {chars = "\u001BT",key = "T",mods = "Alt|Shift"}
    {chars = "\u001BU",key = "U",mods = "Alt|Shift"}
    {chars = "\u001BV",key = "V",mods = "Alt|Shift"}
    {chars = "\u001BW",key = "W",mods = "Alt|Shift"}
    {chars = "\u001BX",key = "X",mods = "Alt|Shift"}
    {chars = "\u001BY",key = "Y",mods = "Alt|Shift"}
    {chars = "\u001BZ",key = "Z",mods = "Alt|Shift"}
    {chars = "\u001B1",key = "Key1",mods = "Alt"}
    {chars = "\u001B2",key = "Key2",mods = "Alt"}
    {chars = "\u001B3",key = "Key3",mods = "Alt"}
    {chars = "\u001B4",key = "Key4",mods = "Alt"}
    {chars = "\u001B5",key = "Key5",mods = "Alt"}
    {chars = "\u001B6",key = "Key6",mods = "Alt"}
    {chars = "\u001B7",key = "Key7",mods = "Alt"}
    {chars = "\u001B8",key = "Key8",mods = "Alt"}
    {chars = "\u001B9",key = "Key9",mods = "Alt"}
    {chars = "\u001B0",key = "Key0",mods = "Alt"}
    {chars = "\u0000",key = "Space",mods = "Control"}
    {chars = "\u001B`",key = "`",mods = "Alt"}
    {chars = "\u001B~",key = "`",mods = "Alt|Shift"}
    {chars = "\u001B.",key = "Period",mods = "Alt"}
    {chars = "\u001B*",key = "Key8",mods = "Alt|Shift"}
    {chars = "\u001B#",key = "Key3",mods = "Alt|Shift"}
    {chars = "\u001B>",key = "Period",mods = "Alt|Shift"}
    {chars = "\u001B<",key = "Comma",mods = "Alt|Shift"}
    {chars = "\u001B_",key = "Minus",mods = "Alt|Shift"}
    {chars = "\u001B%",key = "Key5",mods = "Alt|Shift"}
    {chars = "\u001B^",key = "Key6",mods = "Alt|Shift"}
    {chars = "\u001B\\",key = "Backslash",mods = "Alt"}
    {chars = "\u001B|",key = "Backslash",mods = "Alt|Shift"}
]


[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 0
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Fullscreen"

[window.dimensions]
columns = 100
lines = 75

[window.padding]
x = 0
y = 0
